---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    mongodb_password: "{{  morpheus['customOptions']['mongodb_password'] }}"
  tasks:         
    - name: MongoDB Deployment
      include_role:
        name: mongo-3_0
